//@version= 4
strategy(title="Pure Stochastic long only", overlay = false, default_qty_type = strategy.percent_of_equity, initial_capital=5000, currency="CAD")

// Date Inputs 
FromMonth = input(defval = 9, title = "From Month", minval = 1, maxval = 12)
FromDay   = input(defval = 1, title = "From Day", minval = 1, maxval = 31)
FromYear  = input(defval = 2019, title = "From Year", minval = 2017)
ToMonth   = input(defval = 1, title = "To Month", minval = 1, maxval = 12)
ToDay     = input(defval = 1, title = "To Day", minval = 1, maxval = 31)
ToYear    = input(defval = 2021, title = "To Year", minval = 2018)

// INPUTS & calculations
length = input(10, minval=1)
OverBought = input(70, minval = 50, step = 5)
OverSold = input(30, minval = 10, step = 5)
smoothK = input(9, minval=1)
smoothD = input(4, minval=1)
k = sma(stoch(close, high, low, length), smoothK)
d = sma(k, smoothD)
capital = input(100, defval = 100, minval = 1, maxval = 10000, title = "Capital, %")

// Date Range Control
start     = timestamp(FromYear, FromMonth, FromDay, 00, 00)  
finish    = timestamp(ToYear, ToMonth, ToDay, 23, 59)       
inDateRange() => time >= start and time <= finish ? true : false 

// Entry condition
entryl = k > d and k <= OverSold and close >= high[1]

// Size per trade 
size = strategy.position_size
lot = 0.0
lot := size != size[1] ? strategy.equity / close * capital / 100 : lot[1]

// Entry
strategy.entry("Long", strategy.long, lot, when = entryl)

// Exit conditions 
middle = (OverBought+OverSold)/2
close2= k < d and k > middle
close3 = (k >= OverBought)

// Exit 
strategy.close("Long", when = close2 and inDateRange(), comment ="cross k&d")
strategy.close("Long", when = close3 and inDateRange(), comment = "high value of K")

// Plot graphs
plot(k, color=#0000FF,  linewidth= 2, title="k Stoch")
plot(d, color=#787B86, linewidth= 1, title="d stoch signal")
plot(OverBought)
plot(OverSold)
